[package]
name = "quickreplace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 2.0以前よりも前のバージョンのうち最新のものを使おうとする
text-colorizer = "1"
regex = "1"